#ifndef S_DEFS4_FLAG_H
#define S_DEFS4_FLAG_H
#pragma pack(push, 1)

#define wy1      val[0]
#define wy2      val[1]
#define wz1      val[2]
#define wz2      val[3]
#define wz3      val[4]
#define wz4      val[5]
#define ik1      val[6]
#define ik2      val[7]
#define wk1      val[8]
#define wk2      val[9]
#define beta1    val[10]
#define gamma2   val[11]
#define f        val[12]
#define alfa(aa) val[13 + aa - 1]

#pragma pack(pop)
#endif