#pragma pack(push, 1)

#define NumTypeSys     Schema.TypeSystem.Num
#define KSW            Schema.TypeSystem.QuantityStep
#define NSW(I)         Schema.TypeSystem.NumStep[(I)]

#define	NPRT           Schema.TypeSE

#define	KELRS          Schema.QuantityElem
#define	KURS           Schema.QuantityNode
#define	KUSE           Schema.QuantityNodeSE

#define	KKN            Schema.QuantityCraneForce
#define	KTN            Schema.QuantityBrakeForce
#pragma pack(pop)
