#define  SF1 emwf[0]
#define  CF1 emwf[1]
#define  SL  emwf[2]
#define  A   emwf[3]
#define  B   emwf[4]
#define  ZR  emwf[5]
#define  TET emwf[6]
#define  REZ emwf[7]
#define  E   emwf[8]
#define  NU  emwf[9]
#define  DEL emwf[10]
#define  R   emwf[11]

#define TETA0 teta[0] /* угол относит.веpтикальн.оси 1-го узла КЭ   */
#define UG    teta[1] /* угол относит.веpтикальн.оси 2-го узла КЭ   */
#define Z     teta[2] /* пpиpащение кооpдинаты Z относит. 1-го узла */
#define X     teta[3] /* пpиpащение кооpдинаты X относит. 1-го узла */

