      struct D3EMSL *pd3emsld;

#define  DSLP_EM     pd3emsld->p_em
#define  DNZEMSL     pd3emsld->nzemsl
#define  DSLE1       pd3emsld->e1
#define  DSLE2       pd3emsld->e2
#define  DSLE3       pd3emsld->e3
#define  DSLNU12     pd3emsld->nu12
#define  DSLNU21     pd3emsld->nu21
#define  DSLNU13     pd3emsld->nu13
#define  DSLNU31     pd3emsld->nu31
#define  DSLNU23     pd3emsld->nu23
#define  DSLNU32     pd3emsld->nu32
#define  DSLG12      pd3emsld->g12
#define  DSLG13      pd3emsld->g13
#define  DSLG23      pd3emsld->g23
#define  DSLDELTA    pd3emsld->delta
#define  DSLOMEGA    pd3emsld->omega
